### ISSUE TITLE
Sharing State with other Shared State Hooks

### ISSUE THREAD

**Issue by vf-telwing** [qosenergy/shared-store-hook#5]
How would you approach modifying the state of one store from another? Is this a sign that the states should be merged into one? Please see a contrived example below (with an obvious misuse of hooks):

```javascript
const useUser = createSharedStoreHook(...);
const useCart = createSharedStoreHook({
  actions: {
    updateCartBasedOnUserState() {
       // const [userState] = useUser();
       // ...
    }
  },
})
```

**Comment by ElRatonDeFuego** [comment]
Hi @vf-telwing , thanks for your interest in this lib.

To use store A to modify the state of store B you have several options.

As you mentioned, you could have only one store instead, and use mapState functions so as to only be updated on certain changes, for instance. But that could be confusing if the stores are for different "domains" of your app.

You could also use hook composition: have a third hook C that calls both A & B, retrieving the actions from B (and the state if needed) and returning both the state and actions from A (just as if you'd called A directly), but with one action added or overloaded so as to use an update action from B.

Based on the same idea, but more "compact": instead of returning hook A from a file, B from another, and composing them in yet another file C, you could change the file creating hook A so that you first create an "intermediate" hook - that you don't return from the file -, say A', and then create another one called A in the same file - that you *do* return -, that calls both A' and B.

You can either arrange for an action of A' to accept a setter from B as an argument, or just add/overload an action in A that calls a setter from B.

I could share a Codesandbox example of this if you'd like one.

**Comment by vf-telwing** [comment]
Hi @ElRatonDeFuego thank you for your work on this. I am enjoying it so far.

If you have time, a Codesandbox would be much appreciated. I'm still having trouble understanding how you would access the state/actions when it seems the store is well-encapsulated within each shared hook.

**Comment by ElRatonDeFuego** [comment]
Hi @vf-telwing , [here's a working Codesandbox example](https://codesandbox.io/s/shared-store-hook-update-store-b-from-store-a-yyuux?file=/src/state/useStoreA.ts)

I've whipped it up from a previous box so it may be a bit messy, but I hope it's still useful. If this doesn't answer your question, I'll gladly elaborate.

Please note that in this example you can not use `mapState` or `mapActions` functions on `useStoreA` - I've done this so as keep the code as simple as possible, but know that it is also possible to add these in.

**Comment by vf-telwing** [comment]
Thank you @ElRatonDeFuego ! I see what you mean by "intermediate" hook now. Would the `mapState`/`mapActions` functionality come from something in `shared-store-hook`, or would it need to be implemented in `useStoreA` from scratch?

**Comment by ElRatonDeFuego** [comment]
Yes, you'd just need to accept mapState/mapActions as parameters to `useStoreA()` and pass them on to `useIntemediateStoreA()`

**Comment by vf-telwing** [comment]
Thanks again for all your help @ElRatonDeFuego !

**Comment by vf-telwing** [comment]
Hey @ElRatonDeFuego , I finally got around to trying out the mapState/mapActions forwarding and I'm having some trouble figuring out what the types look like. Also, if I forward both mapping functions, Typescript only seems to be recognizing the return value as `SharedStoreActions`.

```typescript
type HookAState = { /*...*/ };
const actions = (store: SharedStore<HookAState>) => {/* ... */};
const useHookA = createSharedStoreHook<HookAState, typeof actions>({
  actions: actions,
});

function useHookB(
  mapState?:
    | ((state: HookAState) => HookAState)
    | Array<(state: HookAState) => HookAState>
    | typeof ActionsOnly
    | typeof NoActions,
  mapActions?:
    | ((
        actions: typeof actions
      ) => Partial<typeof actions>)
    | typeof NoActions
) {
  // Cannot be destructured because type is Partial<SharedStoreActions<HookAValue, ActionsFromSharedStore<HookAValue>>>
  const [state, actions] = useHookA(
    mapState, // Type 'unique symbol' is not assignable to '((state: HookAState) => unknown)[] | undefined'
    mapActions
  );
}
```

**Comment by ElRatonDeFuego** [comment]
Hi @vf-telwing, yes, this can get a bit tricky, I'll try to reply with an example later today.

**Comment by ElRatonDeFuego** [comment]
As you can see from the doc and the types, a hook like `useHookA` in your example can take 0 to 2 arguments, the first one can be of 5 different sorts, the second one, of 3 different sorts, and that gives us, not 15, but 10 different combinations of arguments - as some combinations wouldn't make sense -, as reflected in the `UseSharedStoreHook` type.

Then, the return values from calling `useHookA` can also be of 3 different natures : only actions (potentially mapped), only state (potentially mapped), or a tuple `[mappedState, mappedActions]`.

Then, the mapping done in `mappedState` results in either a single value or an array of values..

All this to say, trying to reproduce all the possible cases in your `useHookB` above would result in something unsavory ;)

For instance, you're saying `[state, actions] = useHookA(..`, but there's no guarantee you're getting an array back from the call, depending on the values of the mapping functions. You'd have to reproduce what the lib does internally to match its exact behavior.

Fortunately, you probably don't have to :)

When writing something like your `useHookB`, chances are you already know how it's going to be called. You know whether you need the state from `useHookA` or not, whether you need to map it or not, whether this mapping will result in an array or not, etc. So you can boil it down.

Here's an example where I only allow a non-array `mapState` to go through, and no `mapActions` (because it's trivial and doesn't cause re-renders if you don't use it) : 

https://codesandbox.io/s/shared-store-hook-update-store-b-from-store-a-forward-simple-mapstate-5q3h3?file=/src/state/useStoreA.ts

Tell me if this answers your question, or if you need more info. Cheers!

**Comment by vf-telwing** [comment]
@ElRatonDeFuego Yes, the non-array example definitely makes sense. The array version is giving me a bit more trouble though. I currently can't get past `useStoreA` requiring that the `mapState` functions return the `MappedState` array.

Modified `useStoreA` from your example:
```typescript
export const useStoreA = <MappedState = State>(
  mapState?: Array<((state: State) => MappedState)>
): [
  MappedState,
  SharedStoreActions<State, Actions> & {
    setStateForStoreB: ReturnType<typeof useStoreBActions>['setState'];
  }
] => {
  const [state, intermediateActions] = useIntermediateStoreA<MappedState>(mapState);

  const { setState: setStateForStoreB } = useStoreBActions();

  return [state, { ...intermediateActions, setStateForStoreB }];
};
```

And then in `StoreA.tsx`:
```typescript
const [/* ... */] = useStoreA<[number, string]>([
  (state) => state.num, // Type number is not assignable to [number, string]
  (state) => state.str,  // Type string is not assignable to [number, string]
]);
```

**Comment by ElRatonDeFuego** [comment]
Here's a working example using array mapping: https://codesandbox.io/s/shared-store-hook-update-store-b-from-store-a-forward-mapstate-array-39tjg?file=/src/state/useStoreA.ts

Tell me if something's not clear for you - types can sometimes be infuriating.

**Comment by vf-telwing** [comment]
It would have been a long time before I considered `Array<(state: State) => unknown>` :) So once again, thank you @ElRatonDeFuego !
